version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: notas_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    networks:
      - net
  adminer:
    container_name: adminer
    restart: always
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - net

networks:
  net:
    driver: bridge