version: '3'
services:
  app:
    restart: always
    container_name: app_notas_service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notas_db
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    depends_on:
      - db
    networks:
      net:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: notas_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    networks:
      - net
  adminer:
    container_name: adminer
    restart: always
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - net

networks:
  net:
    driver: bridge